### ISSUE TITLE
Libraries view returns: Request failed with status code 406.

### ISSUE THREAD

**Issue by bendanielsbacka** [sassoftware/vscode-sas-extension#252]
**Describe the bug**
Libraries are not visible at all after connecting to sas viya 3.5 server with valid profile. When trying to click refresh button the same 406 status code appears. Using Remote - SSH connection to SAS Viya server ("local" git-repo there) same operation produces "Request failed with status code 401".

**Steps to reproduce**

1. Connect to SAS Viya 3.5 server with valid user profile successfully
2. Click SAS-extension tab and click refresh button at libraries section
3. Libraries section is empty and "Request failed with status code 406 appears" (on remote connection 401 appears)

**Expected behavior**
Libraries should appear to libraries section without 406 or 401 status code

**Screenshots**
![image](https://user-images.githubusercontent.com/3509406/233941281-00259971-9578-4b04-a3da-684a643e1a6a.png)
![image](https://user-images.githubusercontent.com/3509406/233987447-1401715e-f17f-41b5-869d-51fda900d8b9.png)

**Environment (please complete the following information):**
Client OS: Windows 10 Enterprise, version 21H2
Extension version: [v0.1.3]
SAS version: Release: 2.2.2-u3. SAS Viya release: V.03.05

**Comment by scnwwu** [comment]
Should be fixed in v0.1.5

**Comment by gygabyte017** [comment]
It still happens on 0.1.5, explorer works but library does not (error 406)

**Comment by bendanielsbacka** [comment]
Hi,

Huge  tha

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
